### PR TITLE
Add support for multi-post messages

### LINKED ISSUE #11: Add support for multi-post messages
Slack's API caps the number of available blocks to 50, which is a max of around 20 events per week. To get around this problem, we should support breaking up posts into multiple slack messages if there are more than 50 blocks

Ideally, we'll need several changes to fix this:
- Instead of storing posts with a primary key of week, we'll need to store them per week + count
  - We'll need to support update existing databases to the new database schema, as well
- We need to support splitting up posts into multiple parts, text and block formats
- We need to support checking with the saved version of the post in the database, in order to determine whether to update them or not

Acceptance Criteria:
- The app can break up posts into multiple slack messages
- There are tests to ensure that posts are broken up into multiple slack messages with less than 50 blocks each
- There are tests that validate that posts are only updated when they change, which may include one part of a series of slack messages

### PR DESCRIPTION
**Pull request by ThorntonMatthewD**
Fixes #11

# Summary
Adds the ability to split events over multiple Slack messages to skirt around Slack's message size restrictions.

- Each message can have a maximum text length of 3000 characters. This is 3/4 of Slack's recommended max of 4k. I wanted to play it safe, but am open to tweaking this. This should keep us well below the block count limit also.
- If a new event is added after initial posts are made for the week that cause there to be a need for additional messages (called "spillover" in the code/comments), then for each Slack channel that **doesn't have posts yet for the following week** a new message is created. The events will still be sorted in their usual order and spread across the n+1 messages.
   - If a Slack channel **DOES** have messages for the following week posted already and this scenario is hit, then an error will be logged. The new event will **not** be posted to Slack. This is because there isn't a way to add messages before existing ones. Maybe in the future we can send out separate messages for any of these stragglers to let viewers know about them.
   
   
https://github.com/hackgvl/slack-events-bot/assets/44626690/0792c026-d33d-416c-952e-17f02486505f

# Testing
Step|Instructions|Expected Results
---|---|---
1|Download the following test data files: [part_1.json](https://raw.githubusercontent.com/ThorntonMatthewD/slack-events-bot/chunk-messages-test-samples/tests/data/part_1.json) [part_2.json](https://raw.githubusercontent.com/ThorntonMatthewD/slack-events-bot/chunk-messages-test-samples/tests/data/part_2.json)<sup>1</sup>|Test data files are downloaded to your project root.
2|Change `https://events.openupstate.org/api/gtc` on [this line](https://github.com/ThorntonMatthewD/slack-events-bot/blob/5a5dade877ec693a7b5748a4a32ec94db21b5205/src/bot.py#L192) of code to the following: `http://localhost:5544/events`|The URL for where to grab events from is updated.
3|Start json-server with the contents of `part_1.json` as the data source: `npx json-server --port 5544 --watch part_1.json`|json-server is running. Navigating to  http://localhost:5544/events should show all of the events from the JSON file.
4|Load up your local instance of the Slack bot|You should see two messages appear in your subscribed channel(s). See the video attachment above for a sampling of roughly what you should see.
5|Shut down json-server. Reload it with `part_2.json` this time. Restart your Slack bot.|You should see the second message having been updated, and a third one added, in your channel from before.
6|Change some of the value in `part_2.json` for events that are set to take place this week. Restart the Slack bot|Your changes should take effect the messages that had been previously posted.
7|Delete (`rm slack-events-bot.db`) or move (`mv slack-events-bot.db something-different.db`) your sqlite DB.|The DB is reset.
8|Repeat steps 3 and 4|Two new messages, with the same contents as before, have been posted into your Slack channel.
9|Add a message to your `messages` table with a `week` value that's the datetime of the next week.<sup>2</sup>|You should have a new message in your `messages` table for the next week.
10|Repeat step 5|You should see an [error](https://user-images.githubusercontent.com/44626690/277854172-1e6836bc-0371-4a6a-88ea-ef549ac307e8.png) reported to STDERR.

<sup>1</sup> curl commands for convenience:
```bash
curl -L https://raw.githubusercontent.com/ThorntonMatthewD/slack-events-bot/chunk-messages-test-samples/tests/data/part_1.json -o part_1.json

curl -L https://raw.githubusercontent.com/ThorntonMatthewD/slack-events-bot/chunk-messages-test-samples/tests/data/part_2.json -o part_2.json
```

<sup>2</sup> Query for adding a new message for next week (at the time of posting this):
```sql
INSERT INTO messages (
  week, message, message_timestamp, channel_id, sequence_position
) VALUES (
  '2023-10-29 00:00:00+00:00',
  'I am here to be an impediment',
  '1698591600.954199',
  1,
  1
 )
 ```

# Deployment Considerations
A new column has been added to the `messages` table. The following query will need to be executed.
```sql
ALTER TABLE messages ADD sequence_position INTEGER DEFAULT 0 NOT NULL;
```

### CODE REVIEW

**Review by oliviasculley — APPROVED** [review]
This looks great, but we'll need to hold off on merging this until we can reinitialize the db on Jim's instance for a proper deploy

**Comment by ThorntonMatthewD** [comment]
> This looks great, but we'll need to hold off on merging this until we can reinitialize the db on Jim's instance for a proper deploy

Thank you so much! :smile:

**Comment by allella** [comment]
If you want to drop some commands to run on the production app, then I can run them whenever.

**Comment by ThorntonMatthewD** [comment]
@allella Thank you!

Does the VM already have `sqlite3` installed?

If not, and if it's running a Debian-based OS, then `sudo apt install sqlite3` should take care of that.

Opening the SQLite console:
```bash
sqlite3 path/to/slack-events-bot.db
```

Queries to execute
```sql
-- Add the new sequence_position column to the messages table.
ALTER TABLE messages ADD sequence_position INTEGER DEFAULT 0 NOT NULL;

-- Backfill sequence_position values for messages created prior to this release.
UPDATE messages SET sequence_position = 0 WHERE sequence_position IS NULL;
```

After those queries are run then these set of changes should be good to deploy! I think watchtower should pick up on them automatically once they are merged.

**Comment by allella** [comment]
Yes, we have SQLite3 installed.

It sounds like Olivia said we'd do this in person at the HG Labs event, but I'll double-check in the Slack.

**Comment by ThorntonMatthewD** [comment]
If this works with you all, I think next week may be an opportune time to deploy this piece. Something that may occur whenever these changes are shipped is that any weeks still in range could have their events posts "chunked", which could cause things to become slightly out of order (a post 2 of 2 being newly placed at the end of the channel). Since next week should be light on events due to Thanksgiving it should make it less jarring.

**Comment by allella** [comment]
I can run the SQLite commands now, or early tomorrow, if that's the pre-requisite for the merge and deployment of the image.

**Comment by ThorntonMatthewD** [comment]
@allella Thank you! That would be wonderful. Adding the new column will not affect the bot as it stands currently, and we could then merge in these changes maybe Sunday morning? I think if it were merged prior then the second half of the events for the week of the 12th would be reposted.

**Comment by allella** [comment]
@ThorntonMatthewD I've run the two SQL commands above.

**Comment by ThorntonMatthewD** [comment]
@allella Thank you! I will proceed with the merge. 🙌

**Pull request merged**
