### PR TITLE
Switch to Consuming New Events API

### PR DESCRIPTION
**Pull request by ThorntonMatthewD**
# Summary
Sets the Slack bot to pull events data from the new Events API that is/will be hosted at https://stage.hackgreenville.com/api/v0/events.

This updated implementation is brought about by https://github.com/hackgvl/hackgreenville-com/pull/186 and the incredible work of @bogdankharchenko.

Please do not merge this PR until the changes are live at the aforementioned address.

### CODE REVIEW

**Comment by allella** [comment]
Is / should this be an environment / configuration value instead of being hard coded?

**Comment by ThorntonMatthewD** [comment]
> Is / should this be an environment / configuration value instead of being hard coded?

It's not, but it definitely can be!

**Comment by ThorntonMatthewD** [comment]
I've posted a couple of minor issues I've found with the Slack Bot + new Events API on Slack [here](https://hackgreenville.slack.com/archives/C3XNGDEBT/p1702254506949449?thread_ts=1702252523.086379&cid=C3XNGDEBT).

I'll post them here also:
- https://stage.hackgreenville.com/api/v0/events?start_date=2023-12-03&end_date=2023-12-09 doesn't show the items for 12-09-2023, so the end date isn't inclusive (end_date=2023-12-09 is up to and including Dec 9th, 2023 00:00:00 which misses out on the rest of the day). It might be something we'd want to tweak, but since a consumer can just bump the day up one in their query I'm considering this a super low severity item.
- The \<p\> tags that encapsulate event descriptions aren't trimmed like they appear to have been in the prior implementation, and so they show up in the Slack bot output.
   - There is a PR open for the Slack bot to trim HTML tags from the middle of descriptions: https://github.com/hackgvl/slack-events-bot/pull/19. It has kind of stalled out as the original contributor hasn't been responsive, so I'm wondering how we should proceed. It should fix this issue.
      - Should this sanitization be done server side or should every client of the API be responsible for cleaning up the descriptions as they see fit?
   - Also a very low severity
   
The date range params aren't currently used by the Slack bot so really the only issue is the extra HTML tags popping up in posts. Since work has already been started in #19 to fix HTML tags in descriptions in whole I am wondering what the next steps are to get that work ready for launch. :rocket: 

Overall I feel good about the prospect of this PR being merged, but I wanted to make sure I'm being transparent with potential concerns so that whomever reviews this piece can make an informed decision.

**Comment by allella** [comment]
@ThorntonMatthewD we don't currently have a .env or .envrc on the live system. 

Should one of these be setup in advance of the next merge, or are these variables somehow securely sourced from inside the container using a key store?

**Comment by ThorntonMatthewD** [comment]
@allella How is the Slack token and signing secret currently stored? I can make sure the Events API URL is set up to pull from the same source for consistency.

**Comment by allella** [comment]
The environment are in docker-compose.yml

```
services:
    slack-events-bots:
        environment:
```

**Comment by ThorntonMatthewD** [comment]
Okay, perfect! If you include [this line](https://github.com/hackgvl/slack-events-bot/blob/47342185d2bfc9bc0e59cfcf338b74a87eb392c3/docker-compose.yml#L15) in your local copy then that should take care of most of it. I'm not sure if watchtower will pick up on a change made in that manner, so a manual pull of the new image and a rebooting of the container may be in order (a `docker-compose down` and then `docker compose-up -d`).

It'll fall back to using the existing URL if for whatever reason the env var isn't able to be obtained.

**Comment by allella** [comment]
Alright, the new - EVENTS_API_URL=https://stage.hackgreenville.com/api/v0/events has been added to the production.

Should we wait until this is merged to do the pull / down / up commands?

**Comment by ThorntonMatthewD** [comment]
Perfect! Thank you!

Yes, once this PR is merged and the workflow completes with uploading the new Docker image then it will be all set to cycle the container.

**Review by oliviasculley — APPROVED** [review]
Looks good!

**Pull request merged**
